### ISSUE TITLE
App not detecting usb drive

### ISSUE THREAD

**Issue by probwebdev** [artemanufrij/imageburner#14]
![screenshot from 2017-08-07 22-54-54](https://user-images.githubusercontent.com/9195693/29043426-cc54b164-7bc3-11e7-8ef5-183eb69cd608.png)

**Comment by artemanufrij** [comment]
Could you tell me the path of your device? `/dev/???`

**Comment by artemanufrij** [comment]
@rgiyf could you test current master branch, please?

**Comment by probwebdev** [comment]
@artemanufrij I will try it in the evening. Thanks.

**Comment by probwebdev** [comment]
@artemanufrij so I built master branch and it worked. My flash drive /dev/sdc was auto-detected and flashed properly. 
Could you please advise what is the proper way to clean this version and install one from AppCentre??

**Comment by artemanufrij** [comment]
@rgiyf I pushed the fixed version into AppCenter. I hope it will be approved next hours.

Thanks you for your support!
