### ISSUE TITLE
Can we have a 'contractor' to handle ISO-files on right-click?

### ISSUE THREAD

**Issue by greo-d** [artemanufrij/imageburner#16]
Would be nice to write an image on a USB-stick by 'right-click' > 'Open with Imageburner' or 'Write to disk' or something. Is this possible?

**Comment by artemanufrij** [comment]
It's already implemented :smile: 

![bildschirmfoto von 2017-09-28 21 30 50](https://user-images.githubusercontent.com/16517095/30986613-56f851a6-a494-11e7-9a69-febcb6458593.png)

**Comment by greo-d** [comment]
Nooo...not for 'Hashit' :sweat_smile: I mean...for **Imageburner** This is YOUR [Imageburner-repository!! ](https://github.com/artemanufrij/imageburner)  
It would be much easier to write a image with a right-click to disk---like we can already do with gnome-disk-utility. :grimacing:

**Comment by artemanufrij** [comment]
ups... :upside_down_face: 

I'm going to reopen it again...

**Comment by artemanufrij** [comment]
@J0Ar could you test current branch please? I added contactor support:
![unbenannt](https://user-images.githubusercontent.com/16517095/31311782-d0e16e3c-abb3-11e7-9c48-4fb95f3a87d6.png)

**Comment by greo-d** [comment]
@artemanufrij  Works great :+1: Now its so much better and faster to write a iso to usb... :sunglasses:
