### ISSUE TITLE
Feature: Produce the sha256sum

### ISSUE THREAD

**Issue by Philip-Scott** [artemanufrij/imageburner#23]
It would be nice if you could produce the sha256sum of the ISO so that the user can test if the image is valid or not. 

Not sure if other hash functions are used "in the wild", but at least this one is the one recommended at:  https://elementary.io/docs/installation#verify-your-download

**Comment by artemanufrij** [comment]
@Philip-Scott you can:
![bildschirmfoto von 2017-12-04 21 11 10](https://user-images.githubusercontent.com/16517095/33573941-b374e8e0-d937-11e7-8262-35536b9644a7.png)

or do you mean something else?

**Comment by Philip-Scott** [comment]
Yes, you can do it from your hashing app, but it could also be useful if you include it here :) 

Feel free to close it if you don't think it belongs

**Comment by artemanufrij** [comment]
oh....! you are right! :)

**Comment by artemanufrij** [comment]
@Philip-Scott like this?

![bildschirmfoto von 2017-12-05 01 04 07](https://user-images.githubusercontent.com/16517095/33583004-6499ed3a-d958-11e7-9c1b-1697e55ae8ed.png)

**Comment by artemanufrij** [comment]
shipped with last release... :smile:
