### ISSUE TITLE
Can't detect microsd card

### ISSUE THREAD

**Issue by stsdc** [artemanufrij/imageburner#39]

**Comment by artemanufrij** [comment]
@stsdc could you post the unix path please?
`/dev/sdxxx` ?

**Comment by stsdc** [comment]
It is `/dev/mmcblk0`

**Comment by artemanufrij** [comment]
@stsdc could you test current master branch please?
![bildschirmfoto von 2018-03-29 23 04 58](https://user-images.githubusercontent.com/16517095/38113644-dd1d83f0-33a5-11e8-8390-023cdf10722b.png)

**Comment by stsdc** [comment]
Works :+1: 
Tested with microsd (8Gb) and sd hc (4Gb)

**Comment by artemanufrij** [comment]
thank you for your feedback. I'm going to close this issue.

**Comment by stsdc** [comment]
Not working for 8gb GOODRAM
![obraz](https://user-images.githubusercontent.com/6031763/38374442-ec8c60c4-38f3-11e8-930c-3250c5f6d240.png)

But works for 8gb Toshiba and shows microsd icon instead of storage icon in Files
