### ISSUE TITLE
No feedback about why disk section is insensitive

### ISSUE THREAD

**Issue by danirabbit** [artemanufrij/imageburner#4]
There should probably be some label here:

![screenshot from 2017-07-19 10 03 48](https://user-images.githubusercontent.com/7277719/28379746-9f280858-6c69-11e7-8f47-24a76d01145a.png)

**Comment by LonerCactus** [comment]
I've same problem, on latest  stable elementary. Downloads from AppCenter.

**Comment by artemanufrij** [comment]
Fixed in last commit.
https://github.com/artemanufrij/imageburner/commit/71d9115703d6a99c4208f4c64ff2844a123361d5
