### ISSUE TITLE
500 Internal server error when downloading after purchase

### ISSUE THREAD

**Issue by sysfu** [artemanufrij/imageburner#62]
This issue seems to have resolved itself on the 2nd download attempt, but I thought I'd file a report for posterity.

![Screenshot from 2019-04-03 09-04-32](https://user-images.githubusercontent.com/829699/55501689-d62ff780-55ff-11e9-895c-fd9a7dda8c60.png)

**Comment by artemanufrij** [comment]
I guess it was an AppCenter issue...
